// Ready-made sequences: every step is fully written so a rep only has to work the task.
// Generic sales copy for youth sports, gymnastics, dance, and martial arts studios. No customer
// names, prices, or partner names (this repository is public). Fill [brackets] with real facts only.
// Merge fields: {{contact}} (first name, or "there"), {{account}}, {{city}}, {{stage}}, {{my_name}}, {{my_title}}, {{my_phone}}.

const L = (...lines) => lines.join("\n");
const SIGN = L("{{my_name}}", "{{my_title}}, TideLine Strategies", "{{my_phone}}");

export const SEQUENCE_LIBRARY = [
  {
    key: "cold-outreach", name: "New studio outreach (cold)", audience: "prospect",
    description: "16 days, 8 touches. For studios that don't know us yet. Goal: book a 20-minute discovery call.",
    steps: [
      { day: 0, type: "Cold call", title: "Intro call to {{account}}", script: L(
        "GOAL: book a 20-minute discovery call with the owner.",
        "",
        "OPENER: \"Hi {{contact}}, this is {{my_name}} with TideLine Strategies. I'll be quick. We help studios like {{account}} take the repetitive admin off the front desk: makeups, late adds, re-keying rosters, chasing balances. Is that something that eats your team's time?\"",
        "",
        "IF YES, ASK:",
        "- \"What does your front desk spend the most time on each week?\"",
        "- \"How are makeups handled today, start to finish?\"",
        "- \"How many systems does your team touch in a normal day?\"",
        "",
        "ASK FOR THE MEETING: \"It sounds like it's worth 20 minutes to see what we'd take off their plate. Does [day] at [time] or [day] at [time] work better?\"",
        "",
        "OBJECTIONS:",
        "- \"We already have software.\" → \"Most studios we work with do. We usually work alongside it first and automate the hand-offs between systems. Which part of it creates the most extra work?\"",
        "- \"Too busy.\" → \"Totally understand, that's usually why people talk to us. Is mornings or afternoons better next week?\"",
        "- \"Send me info.\" → \"Happy to. So I send the right thing: what's the one task you'd most like off the front desk?\" (then book the follow-up)",
        "",
        "VOICEMAIL (20 sec): \"Hi {{contact}}, {{my_name}} with TideLine Strategies. We help studios get hours back from front-desk admin. I'll send a short email; my number is {{my_phone}}.\"") },
      { day: 0, type: "Email", title: "Intro email (same day as the call)", script: L(
        "Subject: Less admin at {{account}}",
        "",
        "Hi {{contact}},",
        "",
        "I just tried you by phone. I work with studios in and around {{city}} on one thing: taking repetitive admin off the front desk, like makeups, late adds, roster updates, and balance follow-up, with a staff member approving every change.",
        "",
        "Would 20 minutes next week be worth it to see whether that fits {{account}}?",
        "",
        SIGN) },
      { day: 2, type: "LinkedIn", title: "Connect on LinkedIn", script: L(
        "Send a connection request to the owner or decision maker with this note (under 300 characters):",
        "",
        "\"Hi {{contact}}, I work with studio owners on cutting front-desk admin. I'd like to connect and share what's working for other studios near {{city}}. {{my_name}}\"") },
      { day: 3, type: "Phone call", title: "Follow-up call", script: L(
        "GOAL: reach the owner; reference the email.",
        "",
        "OPENER: \"Hi {{contact}}, {{my_name}} with TideLine. I sent a note on Monday about front-desk admin. Did it land?\"",
        "",
        "ASK: \"If you could take one recurring task off your team this season, what would it be?\"",
        "",
        "If they name one: \"That's exactly what we look at in the first 20 minutes. [Day] or [day]?\"",
        "",
        "If gatekeeper: \"Who handles decisions about the software and systems the front desk uses? When is the best time to catch them?\" Log the name as a contact.",
        "",
        "VOICEMAIL: \"Hi {{contact}}, {{my_name}} again from TideLine. Quick question about how {{account}} handles makeups. {{my_phone}}.\"") },
      { day: 5, type: "VITO letter", title: "VITO letter to the owner", script: L(
        "Mail it (a printed letter stands out) or email it to the owner. One page, results first, a specific ask.",
        "",
        "Subject: [Number] hours a week back for {{account}}'s front desk",
        "",
        "Dear {{contact}},",
        "",
        "Studios like {{account}} lose [number] staff hours every week to work that happens between systems: makeups, late adds, re-keying rosters, and chasing balances.",
        "",
        "At [comparable studio], we took [specific task] off the front desk with automation that still asks a staff member to approve every change. In the first [weeks], their team got back an estimated [number] hours a week.",
        "",
        "I'd like 20 minutes to show you what that could look like at {{account}}. I'll call your office on [day] at [time]. If another time is better, reply with what works.",
        "",
        SIGN,
        "",
        "P.S. We measure your team's time for two weeks first, so every savings number is proven, not promised.") },
      { day: 8, type: "Phone call", title: "Call on the day you promised in the letter", script: L(
        "Call exactly when the letter said. This is your strongest call.",
        "",
        "OPENER: \"Hi {{contact}}, {{my_name}} from TideLine Strategies. I'm calling at the time I mentioned in my letter. Did you get a chance to see it?\"",
        "",
        "ASK: \"What would it mean for your team to get [a few] hours back each week?\"",
        "",
        "CLOSE: \"Let's put 20 minutes on the calendar. I'll show you exactly where those hours come from at {{account}}.\"") },
      { day: 11, type: "Email", title: "Value email: one idea", script: L(
        "Subject: An idea for {{account}}",
        "",
        "Hi {{contact}},",
        "",
        "One pattern we see at studios like yours: makeups and same-day changes get handled in three places (the class software, a spreadsheet, and someone's inbox), so they take three times as long.",
        "",
        "We connect those steps so the front desk reviews and approves instead of re-typing. Owners usually see it in the first two weeks.",
        "",
        "Worth a quick look?",
        "",
        SIGN) },
      { day: 16, type: "Email", title: "Close the loop", script: L(
        "Subject: Should I close your file?",
        "",
        "Hi {{contact}},",
        "",
        "I haven't been able to connect, so I'll assume now isn't the right time. If that changes, just reply to this email and I'll set something up.",
        "",
        "Either way, best of luck with the season at {{account}}.",
        "",
        SIGN) },
    ],
  },
  {
    key: "warm-lead", name: "Warm lead fast follow-up", audience: "prospect",
    description: "5 days, 5 touches. For referrals, inbound requests, and event leads. Speed wins: call within the hour.",
    steps: [
      { day: 0, type: "Phone call", title: "Call within the hour", script: L(
        "GOAL: book discovery while interest is high.",
        "",
        "OPENER (referral): \"Hi {{contact}}, {{my_name}} with TideLine Strategies. [Referrer] suggested I reach out; they thought we could help {{account}} the way we helped them.\"",
        "OPENER (inbound/event): \"Hi {{contact}}, {{my_name}} with TideLine. Thanks for [reaching out / stopping by at the event]. I wanted to follow up personally.\"",
        "",
        "ASK: \"What prompted you to look at this now?\" and \"What would a great outcome look like six months from now?\"",
        "",
        "CLOSE: \"Let's set 20 minutes so I can understand how {{account}} runs today. [Day] or [day]?\"") },
      { day: 0, type: "Email", title: "Thank-you email with times", script: L(
        "Subject: Great to connect, {{contact}}",
        "",
        "Hi {{contact}},",
        "",
        "Thanks for [reaching out / the referral from (name)]. I'd like to learn how {{account}} runs today and where your team loses the most time.",
        "",
        "Would any of these work for 20 minutes?",
        "- [Day, time]",
        "- [Day, time]",
        "- [Day, time]",
        "",
        SIGN) },
      { day: 1, type: "Text", title: "Short text if no reply", script: "\"Hi {{contact}}, {{my_name}} from TideLine. Just sent you a few times for a quick 20-minute call about {{account}}. Does one of them work?\" (Only text if they gave you their mobile number.)" },
      { day: 3, type: "Phone call", title: "Second call", script: L(
        "OPENER: \"Hi {{contact}}, {{my_name}} with TideLine. Following up on my email with a few times. What does your week look like?\"",
        "",
        "VOICEMAIL: \"Hi {{contact}}, {{my_name}} with TideLine. Still keen to find 20 minutes for {{account}}. Call or text me at {{my_phone}}.\"") },
      { day: 5, type: "Email", title: "Last friendly nudge", script: L(
        "Subject: Still interested?",
        "",
        "Hi {{contact}},",
        "",
        "I know the season keeps you busy. If now isn't a good time, just tell me when to check back and I'll put it on my calendar.",
        "",
        SIGN) },
    ],
  },
  {
    key: "after-discovery", name: "After the discovery meeting", audience: "prospect", stopOnMeeting: false,
    description: "10 days, 5 touches. Starts right after a discovery meeting. Goal: agree on next steps and move to validation.",
    steps: [
      { day: 0, type: "Email", title: "Same-day recap", script: L(
        "Send within 2 hours of the meeting.",
        "",
        "Subject: Recap: {{account}} and next steps",
        "",
        "Hi {{contact}},",
        "",
        "Thank you for the time today. Here's what I heard:",
        "- [Pain point 1, in their words]",
        "- [Pain point 2]",
        "- [What a great result looks like for them]",
        "",
        "Next step we agreed on: [next step and date].",
        "",
        "Did I miss anything?",
        "",
        SIGN) },
      { day: 2, type: "Phone call", title: "Confirm the decision process", script: L(
        "GOAL: learn how they decide, so nothing stalls.",
        "",
        "ASK:",
        "- \"Besides you, who else weighs in on a decision like this?\"",
        "- \"What would you need to see to feel confident moving forward?\"",
        "- \"Is there a time of year that's better or worse to make a change?\"",
        "",
        "Log anyone new as a contact on the account.") },
      { day: 4, type: "Email", title: "Proof that matches their pain", script: L(
        "Subject: How [comparable studio] handled [their pain point]",
        "",
        "Hi {{contact}},",
        "",
        "You mentioned [their pain point]. Here's how [comparable studio] handled the same thing: [one or two sentences, real result only].",
        "",
        "Happy to walk you through it on our next call.",
        "",
        SIGN) },
      { day: 7, type: "Phone call", title: "Book the validation meeting", script: L(
        "OPENER: \"Hi {{contact}}, {{my_name}}. I've pulled together what we found. Can we walk through it with you [and the other decision maker]?\"",
        "",
        "CLOSE: \"Let's book 45 minutes. [Day] or [day]?\"") },
      { day: 10, type: "Email", title: "Keep it moving", script: L(
        "Subject: Next step for {{account}}",
        "",
        "Hi {{contact}},",
        "",
        "I want to make sure this stays useful for you. Would [day] at [time] work to review the findings together? If priorities have shifted, just let me know.",
        "",
        SIGN) },
    ],
  },
  {
    key: "reengage", name: "Re-engage a quiet prospect", audience: "prospect",
    description: "21 days, 5 touches. For prospects untouched 30+ days. Lead with something new, never \"just checking in\".",
    steps: [
      { day: 0, type: "Email", title: "Something new since we spoke", script: L(
        "Subject: Something new for {{account}}",
        "",
        "Hi {{contact}},",
        "",
        "When we last talked, [their priority] was on your list. Since then, [one genuinely new thing: a feature, a result at a similar studio, a seasonal idea].",
        "",
        "Is that still a priority this season?",
        "",
        SIGN) },
      { day: 3, type: "Phone call", title: "Call with a reason", script: L(
        "OPENER: \"Hi {{contact}}, {{my_name}} with TideLine. Last time we spoke you mentioned [priority]. I've got a new idea on that. Got two minutes?\"",
        "",
        "ASK: \"What's changed at {{account}} since we last talked?\"") },
      { day: 7, type: "LinkedIn", title: "Engage on LinkedIn", script: "Like or comment thoughtfully on a recent post from the owner or the studio's page. If there's nothing recent, send: \"Hi {{contact}}, saw [something about the studio]. Congrats! Would love to catch up when the timing is right.\"" },
      { day: 14, type: "Phone call", title: "Seasonal angle call", script: L(
        "Use this month's angle from Call prep (for example back-to-school enrollment or summer camp planning).",
        "",
        "OPENER: \"Hi {{contact}}, with [season] coming up, a lot of studios are [seasonal pressure]. How is {{account}} handling it this year?\"") },
      { day: 21, type: "Email", title: "Permission to close or keep in touch", script: L(
        "Subject: Keep in touch?",
        "",
        "Hi {{contact}},",
        "",
        "Should I check back next season, or is now a better time than I think? Either answer is helpful.",
        "",
        SIGN) },
    ],
  },
  {
    key: "processing-savings", name: "Card processing savings review", audience: "prospect",
    description: "10 days, 4 touches. For studios paying high card fees. Goal: get a recent processing statement to review.",
    steps: [
      { day: 0, type: "Phone call", title: "Offer a free statement review", script: L(
        "GOAL: get one recent merchant statement.",
        "",
        "OPENER: \"Hi {{contact}}, {{my_name}} with TideLine Strategies. Quick one: studios we work with often pay more for card processing than they need to. We do a free review of one statement and show you, line by line, what you'd save. Would that be useful?\"",
        "",
        "ASK: \"Roughly how much do families pay by card each month?\" and \"Do you know your current rate?\"",
        "",
        "OBJECTIONS:",
        "- \"We're under contract.\" → \"Good to know. The review still shows what it's costing you, and when the contract ends you'll know exactly where you stand.\"",
        "- \"Our rates are fine.\" → \"You may be right. The review takes 10 minutes of your time, and if you're already at a good rate I'll tell you.\"") },
      { day: 0, type: "Email", title: "How to send the statement", script: L(
        "Subject: Free processing review for {{account}}",
        "",
        "Hi {{contact}},",
        "",
        "Thanks for the time. To run the review, just reply with a PDF of one recent monthly processing statement (any month from the last three is fine).",
        "",
        "I'll come back within two business days with a one-page summary: what you pay today, what you'd pay with us, and the yearly difference.",
        "",
        SIGN) },
      { day: 4, type: "Phone call", title: "Statement follow-up", script: "\"Hi {{contact}}, {{my_name}}. Just checking whether you had a chance to grab that statement. If it's easier, I can walk you through downloading it from your processor's portal right now.\"" },
      { day: 10, type: "Email", title: "Last call for the review", script: L(
        "Subject: Your processing review",
        "",
        "Hi {{contact}},",
        "",
        "Still happy to run your free review whenever it's convenient. One statement is all it takes.",
        "",
        SIGN) },
    ],
  },
  {
    key: "onboarding", name: "New client: first 90 days", audience: "upsell", stopOnMeeting: false,
    description: "90 days, 6 touches. Starts at go-live. Goal: a client who is happy, using everything, and willing to refer.",
    steps: [
      { day: 0, type: "Email", title: "Welcome and what to expect", script: L(
        "Subject: Welcome aboard, {{account}}",
        "",
        "Hi {{contact}},",
        "",
        "Thank you for choosing TideLine. Over the next 90 days we'll move one area at a time, and nothing goes live without your sign-off.",
        "",
        "Your first step: [baseline / data import / first workflow] on [date]. I'll check in along the way.",
        "",
        SIGN) },
      { day: 7, type: "Phone call", title: "Week 1 check-in", script: "ASK: \"How did the first week go? What's one thing that felt clunky?\" Fix or log every issue the same day." },
      { day: 21, type: "Phone call", title: "Week 3: early wins", script: "ASK: \"What's the team using most? What's still being done the old way, and why?\" Note any training needs." },
      { day: 45, type: "Email", title: "Day 45: progress summary", script: L(
        "Subject: {{account}}: your first 45 days",
        "",
        "Hi {{contact}},",
        "",
        "Here's where things stand:",
        "- Live: [areas]",
        "- Measured so far: [real numbers only]",
        "- Next: [areas and dates]",
        "",
        "Anything you'd like us to prioritize?",
        "",
        SIGN) },
      { day: 75, type: "In-person visit", title: "Visit the studio", script: "Stop by during a busy window. Watch the front desk for 20 minutes. Ask staff what they'd change. Bring the owner one concrete improvement." },
      { day: 90, type: "Phone call", title: "Day 90 review and referral ask", script: L(
        "REVIEW: \"Looking back at 90 days, what's been the biggest difference for your team?\" (Write down their exact words; ask if you can quote them.)",
        "",
        "REFERRAL: \"Who's another studio owner you respect who'd want the same results? Would you be comfortable introducing us?\"") },
    ],
  },
  {
    key: "upsell", name: "Existing client check-in and upsell", audience: "upsell",
    description: "14 days, 4 touches. For current clients. Goal: find the next problem to solve and offer the add-on that fits.",
    steps: [
      { day: 0, type: "Email", title: "Check-in with {{account}}", script: L(
        "Subject: How are things at {{account}}?",
        "",
        "Hi {{contact}},",
        "",
        "Checking in to see how everything is running. Is anything still slowing your team down that we could take off their plate?",
        "",
        SIGN) },
      { day: 4, type: "Phone call", title: "Usage review call", script: L(
        "ASK:",
        "- \"What's working best for the team right now?\"",
        "- \"What still takes manual effort every week?\"",
        "- \"Any new locations, programs, or staff coming up?\"",
        "",
        "Match their answer to an add-on from Clients to grow on the Today tab. Don't pitch on this call; just confirm the problem.") },
      { day: 10, type: "Email", title: "The add-on that fits", script: L(
        "Subject: An idea based on our call",
        "",
        "Hi {{contact}},",
        "",
        "You mentioned [their problem]. [Add-on] handles exactly that: [one-sentence benefit in their terms].",
        "",
        "Want me to show you in 15 minutes?",
        "",
        SIGN) },
      { day: 14, type: "Phone call", title: "Follow up on the add-on", script: "\"Hi {{contact}}, did you get a chance to look at the idea I sent? I can set up a short demo or a trial so your team can see it with your real data.\"" },
    ],
  },
  {
    key: "renewal", name: "Renewal (start 60 days before term end)", audience: "upsell", stopOnMeeting: false,
    description: "55 days, 4 touches. Goal: renew early, with any changes agreed, and no surprises.",
    steps: [
      { day: 0, type: "Email", title: "Renewal heads-up and value recap", script: L(
        "Subject: {{account}}: a look back before your renewal",
        "",
        "Hi {{contact}},",
        "",
        "Your term renews on [date]. Before then, I'd like 20 minutes to review the past year: what's worked, what you'd change, and what's next.",
        "",
        "[Two or three real results from the year.]",
        "",
        "Would [day] or [day] work?",
        "",
        SIGN) },
      { day: 7, type: "Phone call", title: "Renewal review", script: "ASK: \"What would make next year even better?\" Confirm the decision maker and any budget timing. Note anything to fix before renewal." },
      { day: 30, type: "Email", title: "Renewal summary", script: L(
        "Subject: Your renewal summary",
        "",
        "Hi {{contact}},",
        "",
        "As discussed: [term, any changes, start date]. Let me know if anything looks off.",
        "",
        SIGN) },
      { day: 55, type: "Phone call", title: "Confirm before the term ends", script: "Confirm the renewal is signed. If it isn't, ask: \"Is there anything holding this up that I can help with?\"" },
    ],
  },
  {
    key: "referral", name: "Referral ask from a happy client", audience: "upsell", stopOnMeeting: false,
    description: "10 days, 3 touches. Use after a client shares a win. Goal: one warm introduction.",
    steps: [
      { day: 0, type: "Phone call", title: "Ask for an introduction", script: L(
        "Ask right after they mention a win.",
        "",
        "\"{{contact}}, I'm glad it's making a difference. Most of our new clients come from owners like you. Who's one studio owner you know who'd want the same thing? Would you be open to a quick introduction?\"",
        "",
        "If yes: get the name and the best way to reach them, then log them as a new account and contact.") },
      { day: 1, type: "Email", title: "Make the introduction easy", script: L(
        "Subject: An easy intro",
        "",
        "Hi {{contact}},",
        "",
        "Thanks again for offering to introduce me to [name]. Here's a short note you can forward or edit:",
        "",
        "\"[Name], I've been working with {{my_name}} at TideLine Strategies and it's taken a lot of admin off our front desk. Thought you'd want to talk to them.\"",
        "",
        SIGN) },
      { day: 10, type: "Email", title: "Thank-you", script: L(
        "Subject: Thank you",
        "",
        "Hi {{contact}},",
        "",
        "Thank you for the introduction to [name]. It means a lot. I'll keep you posted.",
        "",
        SIGN) },
    ],
  },
];
